---
name: "JK-BMS wired management"
version: 2.0.1
slug: "smartphoton_jkbms"
description: JK-BMS management via RS485 & Ip Gateway
url: https://domosimple.eu/forum/forum-32.html
ingress: false
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2025.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "1891/tcp": 1891
ports_description:
  "1891/tcp": Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
options:
  # Configuration JKBMS
  jkbms:
    jkbms_path: "/dev/ttyUSBx"
    jkbms_count: 1
    use_gateway: false
    gateway_ip: "192.168.1.100"
    gateway_port: 5000
    bms_broadcasting: true
    CAN_bus_usage: false
  # Configuration MQTT
  mqtt:
    mqttadresse: "core-mosquitto.local.hass.io"
    mqttport: 1883
    mqttuser: "username"
    mqttpass: "password"
  # Configuration SSL
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  # Configuration JK-BMS
  jkbms:
    jkbms_path: str
    jkbms_count: int(1,10)?
    use_gateway: bool
    gateway_ip: str?
    gateway_port: int(1,65535)?
    bms_broadcasting: bool
    CAN_bus_usage: bool
  # Configuration MQTT
  mqtt:
    mqttadresse: str?
    mqttport: int(1,65535)?
    mqttuser: str?
    mqttpass: password?
  # Configuration SSL
  ssl: bool?
  certfile: str?
  keyfile: str?
