---
name: Smartphoton JK-BMS RS485 management
version: 1.0.3
slug: smartphoton-jk-bms-rs485
description: JK-BMS management via RS485 port
url: https://domosimple.eu/
ingress: false
#ingress_port: 1891
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2023.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  1891/tcp: 1891
ports_description:
  1891/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
options:
  listbatterie:
    - chemin: "false"
      type: serial
      batterie: jkbms
      nbSlave: 1
  mqtt:
    mqttadresse: ""
    mqttport: ""
    mqttuser: ""
    mqttpass: ""

  #lovelace: false
  #panneaux: "panneaux"
  batteries: "batteries"
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  #onduleur: list(voltronic|easun)
  listbatterie:
    - chemin: "str"
      type: list(false|ip|serial|rs485)?
      batterie: list(false|pylontech|jkbms)?
      nbSlave: int?
  mqtt:
    mqttadresse: str?
    mqttport: port?
    mqttuser: str?
    mqttpass: password?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  #lovelace: bool
  #panneaux: str
  batteries: str
  ssl: bool
  certfile: str
  keyfile: str
  not_need: "str?"
  leave_front_door_open: bool?
  safe_mode: bool?
  max_old_space_size: int?
