---
name: "Smartphoton JK-BMS RS485 wired management"
version: 1.1.3
slug: "smartphoton_jkbms"
description: JK-BMS management via RS485 & Rj45 port
url: https://domosimple.eu/forum/thread-917.html
ingress: false
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2023.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  1891/tcp: 1891
ports_description:
  1891/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
options:
  jkbms:
    - path: "/dev/ttyUSBx"
      nb_jkbms: 1
      use_gateway: false
      gateway_ip: ""
      gateway_port: 5000
  mqtt:
    mqttadresse: "core-mosquitto.local.hass.io"
    mqttport: 1883
    mqttuser: "username"
    mqttpass: "password"
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  jkbms:
    - path: str
      nb_jkbms: int(1,)?
      use_gateway: bool?
      gateway_ip: str?
      gateway_port: int(1,65535)?
  mqtt:
    mqttadresse: str?
    mqttport: int(1,65535)?
    mqttuser: str?
    mqttpass: password?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool?
  certfile: str?
  keyfile: str?