---
name: "JK-BMS wired management"
version: 3.0.13
slug: "smartphoton_jkbms"
description: Management via RS485 & CAN bus. Also with an Ip Gateway
url: https://domosimple.eu/forum/thread-917.html
ingress: false
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2025.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
privileged:
  - NET_ADMIN
  - SYS_RAWIO
ports:
  "1891/tcp": 1891
ports_description:
  "1891/tcp": Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl

options:
  # JK-BMS Configuration
  jkbms_path: "/dev/serial/by-id/usb-xxxx_USB_Serial-abcdefghij"
  jkbms_count: 1
  use_gateway: false
  gateway_ip: "192.168.1.100"
  gateway_port: 5000
  communication_debug: false
  bms_broadcasting: false
  CAN_bus_usage: false
  
  # MQTT Configuration
  mqttadresse: "core-mosquitto.local.hass.io"
  mqttport: 1883
  mqttuser: "username"
  mqttpass: "password"
  
  # SSL Configuration
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"

schema:
  # JK-BMS Configuration
  jkbms_path: str
  jkbms_count: int(1,10)?
  use_gateway: bool
  gateway_ip: str?
  gateway_port: int(1,65535)?
  communication_debug: bool
  bms_broadcasting: bool
  CAN_bus_usage: bool
  
  # MQTT Configuration  
  mqttadresse: str?
  mqttport: int(1,65535)?
  mqttuser: str?
  mqttpass: password?
  
  # SSL Configuration
  ssl: bool?
  certfile: str?
  keyfile: str?

# Configuration des groupes visuels
panel_config:
  - name: "JK-BMS Configuration"
    description: "Settings for JK-BMS communication and management"
    fields:
      - jkbms_path
      - jkbms_count
      - use_gateway
      - gateway_ip
      - gateway_port
      - communication_debug
      - bms_broadcasting
      - CAN_bus_usage
  - name: "MQTT Configuration"
    description: "Settings for MQTT broker connection"
    fields:
      - mqttadresse
      - mqttport
      - mqttuser
      - mqttpass
  - name: "SSL Configuration"
    description: "Settings for secure connections"
    fields:
      - ssl
      - certfile
      - keyfile