name: "ðŸ› Bug report"
description: "Report a reproducible problem with the JK-BMS RS485 add-on"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report

        Please fill in as much information as possible so the issue can be diagnosed quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-checks"
      description: "Before opening this bug report, please confirm:"
      options:
        - label: "I have read the README"
          required: true
        - label: "I have read the FAQ.md and did not find the answer"
          required: true
        - label: "I have searched for existing issues"
          required: true

  - type: input
    id: addon_version
    attributes:
      label: "Add-on version"
      description: "The version of the JK-BMS RS485 add-on you are using"
      placeholder: "e.g. v3.x.y or commit hash"
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: "Home Assistant version"
      description: "Your Home Assistant version"
      placeholder: "e.g. 2026.2.0"
    validations:
      required: true

  - type: dropdown
    id: connection_type
    attributes:
      label: "Connection type"
      description: "How is the JK-BMS connected?"
      options:
        - "Direct USB RS485 adapter (FTDI/CH340/CP2102 -> /dev/ttyUSB0)"
        - "Serial adapter showing as /dev/ttyACM0"
        - "TCP/IP gateway (e.g. USR-TCP232, WiFi RS485 bridge)"
        - "Other (please describe below in 'Additional context')"
    validations:
      required: true

  - type: textarea
    id: bms_model
    attributes:
      label: "BMS model(s) and mode"
      description: "Exact JK-BMS model(s) and whether they are slave/master/broadcast/CAN"
      placeholder: |
        Example:
        - JK-BMS, slave mode, address 1
        - JK-BMS, broadcast mode, address 0000
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug description"
      description: "What is going wrong? What did you expect to happen instead?"
      placeholder: |
        Clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Step-by-step instructions to reproduce the issue"
      placeholder: |
        1. Start the add-on
        2. ...
        3. ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs (with DEBUG if possible)"
      description: "Enable DEBUG if possible, restart the add-on, reproduce the issue and paste the logs here"
      render: shell
      placeholder: |
        Please include at least:
        - Add-on startup logs
        - Any error messages or tracebacks
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: "Configuration"
      description: "Your relevant configuration (you can anonymize hostnames/IPs)"
      render: yaml
      placeholder: |
        jkbms_rs485:
          port: /dev/ttyUSB0
          baudrate: 115200
          bms_count: 2
          mqtt_prefix: jkbms/

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Anything else that might be relevant (screenshots, graphs, special hardware, etc.)"
      placeholder: |
        Example:
        - Using a specific RS485 adapter model
        - Using a specific TCP/IP gateway
        - Special inverter / ESS setup
